name: C++ CI

on:
  push:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev cmake libboost-all-dev libpaho-mqtt* libgtest-dev

    - name: Build main code
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
      working-directory: proxy/

    - name: Run unit tests of config module
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
      working-directory: proxy/unitTest/configTest

    - name: Run unit tests of proxy module
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
      working-directory: proxy/unitTest/proxyTest
