name: C++ CI

on:
  push:
    branches:
      - test-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libssl-dev cmake libboost-all-dev libpaho-mqttpp3 libpaho-mqtt3a libpaho-mqtt-dev
    
    - name: Fetch and build Paho MQTT C++ library
      run: |
        git clone https://github.com/eclipse/paho.mqtt.cpp.git
        cd paho.mqtt.cpp
        cmake -Bbuild -H. -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE
        cmake --build build

    - name: Build main code
      run: |
        mkdir -p build
        cd build
        cmake ..
        make
      working-directory: proxy/

    - name: Run unit tests of config module
      run: |
        mkdir -p build
        cd build
        cmake ..
        make test
      working-directory: proxy/unitTest/configTest

    - name: Run unit tests of proxy module
      run: |
        mkdir -p build
        cd build
        cmake ..
        make test
      working-directory: proxy/unitTest/proxyTest
